### ISSUE TITLE
Contrato de software

### ISSUE THREAD

**Issue by Graciela2000** [SistemasTecTlaxiaco/contrato-de-software-contrato-de-software#1]
[Tarea_CONTRATO DE LANZAMIENTO DEL EQUIPO DE DESARROLLO.pdf](https://github.com/SistemasTecTlaxiaco/contrato-de-software-contrato-de-software/files/7716504/Tarea_CONTRATO.DE.LANZAMIENTO.DEL.EQUIPO.DE.DESARROLLO.pdf)

**Comment by Edwin-1012** [comment]
Calificación: 20% 
Contienen todos los puntos necesarios dentro de la práctica.

**Comment by Edwin-1012** [comment]
Calificación de la Wiki: 80%
La documentación se muestra en orden y con los puntos validos del sistema.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
